[general]
import = [
    #"~/.config/alacritty/colors/alacritty-colors.toml"
    #"~/.cache/wallust/alacritty-gruvbox.toml"
     "~/.config/alacritty/dracula.toml"
     #"~/.config/alacritty/modus-vivendi-tinted.toml"
]
[font]

normal = { family = "BlexMono Nerd Font", style = "Regular"}



[selection]
save_to_clipboard = true

[[keyboard.bindings]]
key = "C"
mods = "Control|Alt"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Alt"
action = "Paste"

[window]
decorations = "Buttonless"
opacity = 1.0
[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 10
y = 10


# [colors.primary]
# foreground = "#3c3836"
# background = "#fbf1c7"

# [colors.cursor]
# text = "#fbf1c7"
# cursor = "#3c3836"

# [colors.selection]
# text = "#fbf1c7"
# background = "#3c3836"

# [colors.normal]
# black = "#fbf1c7"
# red = "#cc241d"
# green = "#98971a"
# yellow = "#d79921"
# blue = "#458588"
# magenta = "#b16286"
# cyan = "#689d6a"
# white = "#7c6f64"

# [colors.bright]
# black = "#928374"
# red = "#9d0006"
# green = "#79740e"
# yellow = "#b57614"
# blue = "#076678"
# magenta = "#8f3f71"
# cyan = "#427b58"
# white = "#3c3836"
